#!/usr/bin/env tsx
/**
 * OpenFunction — Documentation Generator
 *
 * Outputs a markdown reference of all registered tools with their schemas.
 * Usage:  npm run docs
 *
 * Prints to stdout — pipe to a file if you want to save it:
 *   npm run docs > TOOLS.md
 */

import { registry } from "../src/register-tools.js";

// ── Generate docs ──────────────────────────────────────────────────────────

const tools = registry.getAll();

console.log("# openFunctions — Tool Reference\n");
console.log(`${tools.length} tools available.\n`);

// Summary table
console.log("| Tool | Description |");
console.log("|------|-------------|");
for (const tool of tools) {
  const desc = tool.description.split(".")[0]; // First sentence only
  console.log(`| \`${tool.name}\` | ${desc} |`);
}
console.log();

// Detailed reference
console.log("---\n");

for (const tool of tools) {
  console.log(`## \`${tool.name}\`\n`);
  console.log(`${tool.description}\n`);

  // Parameters
  const props = tool.inputSchema.properties;
  const required = new Set(tool.inputSchema.required ?? []);
  const paramKeys = Object.keys(props);

  if (paramKeys.length > 0) {
    console.log("**Parameters:**\n");
    console.log("| Name | Type | Required | Description |");
    console.log("|------|------|----------|-------------|");

    for (const [key, schema] of Object.entries(props)) {
      const req = required.has(key) ? "Yes" : "No";
      const desc = schema.description ?? "";
      let type = schema.type;
      if (schema.enum) {
        type = schema.enum.map((e) => `\`${e}\``).join(" \\| ");
      }
      if (schema.type === "array" && schema.items) {
        type = `${schema.items.type}[]`;
      }
      console.log(`| \`${key}\` | ${type} | ${req} | ${desc} |`);
    }
    console.log();
  } else {
    console.log("**Parameters:** None\n");
  }

  // Tags
  if (tool.tags && tool.tags.length > 0) {
    console.log(`**Tags:** ${tool.tags.map((t) => `\`${t}\``).join(", ")}\n`);
  }

  // Tests
  if (tool.tests && tool.tests.length > 0) {
    console.log(`**Tests:** ${tool.tests.length} test case${tool.tests.length === 1 ? "" : "s"}\n`);
  }

  console.log("---\n");
}

console.log(
  "*Generated by openFunctions — " +
    `${new Date().toISOString().split("T")[0]}*\n`
);
